// clang-format off

#pragma once

#define STREAMLINE_DISABLE 0
#define STREAMLINE_ENABLE  1

#define STREAMLINE_LANG_CXX98_FLAG (1 << 1)
#define STREAMLINE_LANG_CXX03_FLAG (1 << 2)
#define STREAMLINE_LANG_CXX0X_FLAG (1 << 3)
#define STREAMLINE_LANG_CXX11_FLAG (1 << 4)
#define STREAMLINE_LANG_CXX14_FLAG (1 << 5)
#define STREAMLINE_LANG_CXX17_FLAG (1 << 6)
#define STREAMLINE_LANG_CXX20_FLAG (1 << 7)

#define STREAMLINE_LANG_CXX98                   STREAMLINE_LANG_CXX98_FLAG           
#define STREAMLINE_LANG_CXX03      (STREAMLINE_LANG_CXX98 | STREAMLINE_LANG_CXX03_FLAG)          
#define STREAMLINE_LANG_CXX0X      (STREAMLINE_LANG_CXX03 | STREAMLINE_LANG_CXX0X_FLAG)                  
#define STREAMLINE_LANG_CXX11      (STREAMLINE_LANG_CXX0X | STREAMLINE_LANG_CXX11_FLAG)
#define STREAMLINE_LANG_CXX14      (STREAMLINE_LANG_CXX11 | STREAMLINE_LANG_CXX14_FLAG)
#define STREAMLINE_LANG_CXX17      (STREAMLINE_LANG_CXX14 | STREAMLINE_LANG_CXX17_FLAG)
#define STREAMLINE_LANG_CXX20      (STREAMLINE_LANG_CXX17 | STREAMLINE_LANG_CXX20_FLAG)

#if   __cplusplus > 201703L 
#       define STREAMLINE_LANG STREAMLINE_LANG_CXX20
#elif __cplusplus == 201703L
#       define STREAMLINE_LANG STREAMLINE_LANG_CXX17
#elif __cplusplus == 201402L
#       define STREAMLINE_LANG STREAMLINE_LANG_CXX14
#elif __cplusplus == 201103L
#       define STREAMLINE_LANG STREAMLINE_LANG_CXX11
#elif __cplusplus == 199711L
#       define STREAMLINE_LANG STREAMLINE_LANG_CXX98
#endif

#if STREAMLINE_LANG & STREAMLINE_LANG_CXX17_FLAG
#       define STREAMLINE_NODISCARD [[nodiscard]]
#else
#       define STREAMLINE_NODISCARD
#endif

#if defined(STREAMLINE_FORCE_WARNING)
#   define STREAMLINE_SILENT_WARNING STREAMLINE_DISABLE
#else
#   define STREAMLINE_SILENT_WARNING STREAMLINE_ENABLE
#endif

#if defined(STREAMLINE_FORCE_INLINE)
#   if STREAMLINE_COMPILER_GCC | STREAMLINE_COMILER_CLANG
#       define STREAMLINE_INLINE __attribute__((__always_inline__))
#       define STREAMLINE_NEVER_INLINE __attribute__((__noinline__))
#   else
#       define STREAMLINE_INLINE inline
#       define STREAMLINE_NEVER_INLINE 
#   endif
#else 
#   define STREAMLINE_INLINE inline
#   define STREAMLINE_NEVER_INLINE 
#endif

#if defined(__GNUC__)
#   define STREAMLINE_CONFIG_ANONYMOUS_STRUCT STREAMLINE_ENABLE
#else
#   define STREAMLINE_CONFIG_ANONYMOUS_STRUCT STREAMLINE_DISABLE
#endif

#define STREAMLINE_SWIZZLE_DISABLED 0
#define STREAMLINE_SWIZZLE_OPERATOR 1
#define STREAMLINE_SWIZZLE_FUNCTION 2

#define STREAMLINE_CONFIG_SWIZZLE STREAMLINE_SWIZZLE_OPERATOR

